### PR TITLE
Sources added inside package for build without Internet.

### PR DESCRIPTION
**Pull request by farcop**
Sources added inside package for build without Internet.
When building in corporate environments, internet access is usually limited.

### CODE REVIEW

**Comment by pniederlag** [comment]
Please don't add unnecessary binary packages that will bloat users with a good setup.

Rather provide documentation and assistance to users to get a proper working setup.

**Comment by farcop** [comment]
It's unpossible to set up it without Internet access.

**Comment by noherczeg** [comment]
#38 might be related

**Comment by 1000ch** [comment]
Solved by #41.

**Pull request closed without merging**
