### PR TITLE
Update libwebp

### PR DESCRIPTION
**Pull request by rejas**

### CODE REVIEW

**Comment by rejas** [comment]
surprise....

**Comment by rejas** [comment]
fixed merge conflicts, rdy to merge once travcis goes green :-)

**Comment by 1000ch** [comment]
Also have to update bundled executable binaries.

**Comment by rejas** [comment]
No updates for linux 32bit available. Delete the old one or what shall we do?

**Comment by rejas** [comment]
Do you have a recommendation what do do about the missing linux32bit binary @1000ch ?

**Comment by rejas** [comment]
HI, got to ask again @1000ch : No updates for linux 32bit available. Delete the old one or what shall we do?

**Comment by 1000ch** [comment]
A bit difficult to decide, but maybe keeping old binaries make sense as support aspect.

**Pull request merged**
